export default {
  GET_EMPLOYEES_LIST: "eList/GET_EMPLOYEES_LIST",
  PUT_EMPLOYEES_LIST: "eList/PUT_EMPLOYEES_LIST",
  SHOW_ERROR_EMPLOYEES_LIST: "eList/SHOW_ERROR_EMPLOYEES_LIST",
  HIDE_ERROR_EMPLOYEES_LIST: "eList/HIDE_ERROR_EMPLOYEES_LIST",
};
