export default {
  GET_EMPLOYEES_LIST: "eReview/GET_EMPLOYEES_LIST",
  PUT_EMPLOYEES_LIST: "eReview/PUT_EMPLOYEES_LIST",
  FAILED_EMPLOYEES_LIST: "eReview/FAILED_EMPLOYEES_LIST",

  CHANGE_ASSIGNEE_INFO: "eReview/CHANGE_ASSIGNEE_INFO",
  CHANGE_SAVING_ASSIGNEE: "eReview/CHANGE_SAVING_ASSIGNEE",
  CHANGED_ASSIGNEE_SAVED: "eReview/CHANGED_ASSIGNEE_SAVED",
  FAILED_CHANGE_ASSIGNEE: "eReview/FAILED_CHANGE_ASSIGNEE",
};
