export default {
  GET_EMPLOYEES_LIST: "eReview/GET_EMPLOYEES_LIST",
  PUT_EMPLOYEES_LIST: "eReview/PUT_EMPLOYEES_LIST",
  SHOW_ERROR_EMPLOYEES_LIST: "eReview/SHOW_ERROR_EMPLOYEES_LIST",
  HIDE_ERROR_EMPLOYEES_LIST: "eReview/HIDE_ERROR_EMPLOYEES_LIST",

  EDITOR_SET_LOADING: "eReview/EDITOR_SET_LOADING",
  EDITOR_SET_EMPLOYEE_FORM: "eReview/EDITOR_SET_EMPLOYEE_FORM",
  EDITOR_CHANGE_FORM: "eReview/EDITOR_CHANGE_FORM",

  EDITOR_SENDING: "eReview/EDITOR_SENDING",
  EDITOR_EDIT_SAVED: "eReview/EDITOR_EDIT_SAVED",

  EDITOR_SHOW_ERROR: "eReview/EDITOR_SHOW_ERROR",
  EDITOR_HIDE_ERROR: "eReview/EDITOR_HIDE_ERROR",
};

export const emptyEmployee = {
  id: -1,
  firstName: "",
  lastName: "",
  email: "",
  manager: "",
  lastReview: null,
};
