export default {
  GET_EMPLOYEES_LIST: "eReview/GET_EMPLOYEES_LIST",
  PUT_EMPLOYEES_LIST: "eReview/PUT_EMPLOYEES_LIST",
  SHOW_ERROR_EMPLOYEES_LIST: "eReview/SHOW_ERROR_EMPLOYEES_LIST",
  HIDE_ERROR_EMPLOYEES_LIST: "eReview/HIDE_ERROR_EMPLOYEES_LIST",

  CHANGE_ASSIGNEE_INFO: "eReview/CHANGE_ASSIGNEE_INFO",
  CHANGE_SAVING_ASSIGNEE: "eReview/CHANGE_SAVING_ASSIGNEE",
  CHANGED_ASSIGNEE_SAVED: "eReview/CHANGED_ASSIGNEE_SAVED",
};
